services:
  elasticsearch:
    build: .
    container_name: es-service
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=true
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es_network
    restart: unless-stopped

volumes:
  es_data:
    driver: local

networks:
  es_network:
    driver: bridge
